---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Tail
no_index:
  directory:
    - t
    - inc
requires:
  File::stat: '0'
  FileHandle: '0'
  IO::Seekable: '0'
  Time::HiRes: '1.12'
version: '1.2'
