.PHONY:all
all:scanf scanf_2 read std

scanf:scanf.c
	@gcc scanf.c -o scanf
scanf_2:scanf_2.c
	@gcc scanf_2.c -o scanf_2
read:read.c
	@gcc read.c -o read

std:std.c
	@gcc std.c -o std 

.PHONY:clean
clean:
	@rm scanf scanf_2 read

