#!/bin/bash
#
# synerys Start up synerys daemon
# 
# chkconfig: 2345 03 99
# description: synery is a tools for share mouse and keyboard between screens
# 

prog="synergys"

PID_FILE=/var/run/synergys.pid
SYNERGYS=/usr/bin/synergys
CONFIG=/etc/synergy.conf

. /etc/rc.d/init.d/functions

function start()
{
	[ -f $PID_FILE ] && exit 1
	[ -x $SYNERGYS ] || exit 5
	[ -f $CONFIG ] || exit 6

	echo -n $"Starting $prog: "
	$prog && sleep 0.2 && success || failure
	echo
	
	xset -dpms
	touch $PID_FILE
	echo `pidof $prog` > $PID_FILE

	return 0
}

function stop()
{
	[ -f $PID_FILE ] || exit 5
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE $SYNERGYS

	echo
}

function restart()
{
	stop
	start
}

function status()
{
	if [ -f $PID_FILE ] ; then
		echo "$prog running---"
	else
		echo "$prog stoped---"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo "no support"
		;;
esac

